### ISSUE TITLE
怎么主题更换字体

### ISSUE THREAD

**Issue by ligj1706** [JackonYang/blog-2020s#1]
主题的字体看起来太纤细了，希望换个字体改善阅读体验，请问怎么更改字体？谢谢

**Comment by JackonYang** [comment]
@ligj1706  没改过，不清楚。

猜测，应该在这个文件里：https://github.com/misc-codes/hexo-theme-xoxo/blob/master/source/css/common.less

**Comment by ligj1706** [comment]
谢谢，主题字体修改是在https://github.com/misc-codes/hexo-theme-xoxo/blob/master/source/css/common.less，已经修改完成

**Comment by ligj1706** [comment]
@JackonYang 谢谢，主题字体修改是在你提示的这个文件里面，已经修改完成
